# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  macos:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |        
        # needed for installing matplotlib
        brew install pkg-config
        pip install -e ".[optional, test, doc]"
        pip install flake8
        pip install --upgrade setuptools
        pip install --upgrade pytest-cov
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E901,E999,F821,F822,F823,W605 --show-source --statistics
        # Some warning codes are ignored because they conflict with black's formatting, or are
        # incompatible with MoviePy's structure
        # E203: whitespace before ':'
        # E302: expected 2 blank lines, found 0
        # E402: module level import not at top of file
        # W291: trailing whitespace
        # W293: blank line contains whitespace
        # W503: line break before binary operator
        flake8 moviepy --ignore=E203,E302,E402,W291,W293,W503 --max-complexity=10 --max-line-length=127 --statistics --count --exit-zero
        # Check examples and tests with slightly relaxed rules to allow 'star' imports
        # F403 'from moviepy.editor import *' used; unable to detect undefined names
        # F405 'name' may be undefined, or defined from star imports: moviepy.editor
        flake8 . --ignore=E203,E302,E402,W291,W293,W503,F403,F405 --exclude moviepy/ --max-complexity=10 --max-line-length=127 --statistics --count  --exit-zero
    - name: Test with pytest
      run: |
        pytest tests/ --doctest-modules -v --cov moviepy --cov-report term-missing
